export const KabulPlaces = {
  Adalat: "عدالت",
  "Ahmad Shah Baba Mina": "احمد شاه بابا مینه",
  "Arzan Qimat": "ارزان قیمت",
  "Arzan Qimat-e-Se": "ارزان قیمت سه",
  Bagrami: "بگرامی",
  "Bagh-e Bala": "باغ بالا",
  Baghlan: "بغلان",
  Banayi: "بنایی",
  "Chahar Qala": "چهار قلعه",
  Chardehi: "چاردهی",
  Charkhi: "چرخی",
  "Chel Dokhtar": "چل دختر",
  "Chihil Sutun": "چهل ستون",
  Chindawol: "چندول",
  Company: "کمپنی",
  Darulaman: "درلومان",
  "Deh Afghanan": "ده افغانان",
  "Deh Sabz": "ده سبز",
  Dehmazang: "ده مزنگ",
  "Haji Yaqub Square": "میدان حاجی یعقوب",
  "Jan Aman": "جان آمن",
  "Kamar Band": "کمربند",
  "Kart-e-Char": "کارت چهار",
  "Karte 4": "کارت ۴",
  "Karte Ariana": "کارت آریانا",
  "Karte Char": "کارت چهار",
  "Karte Char-e-Naw": "کارت چهار نو",
  "Karte Mamoorin": "کارت مأمورین",
  "Karte Naw": "کارت نو",
  "Karte Parwan": "کارت پروان",
  "Karte Parwan-e-Doo": "کارت پروان دو",
  "Karte Sakhi": "کارت صاحی",
  "Karte Seh": "کارت سه",
  "Karte Seh-e-Shahid": "کارت سه شهید",
  "Khair Khana": "خیرخانه",
  "Khwaja Boghra": "خواجه بغرا",
  "Khwaja Rawash": "خواجه رواش",
  "Kolola Pushta": "کلوله پشته",
  Macrorayan: "ماکروریان",
  Malalai: "ملالای",
  Paghman: "پغمان",
  "Parwan-e-Du": "پروان دو",
  "Pul-e-Charkhi": "پل چرخی",
  "Pul-e-Charkhi Industrial Park": "پارک صنعتی پل چرخی",
  "Pul-e-Pachir": "پل پاچیر",
  "Pul-e-Sokhta": "پل سوخته",
  "Puli Bagh-e-Omomi": "پل باغ عمومی",
  Qalacha: "قلاچه",
  "Qala-e-Fathullah": "قلعه فتح الله",
  "Qala-e-Haidar": "قلعه حیدر",
  "Qala-e-Haidar Khan": "قلعه حیدرخان",
  "Qala-e-Mirza": "قلعه میرزا",
  "Qala-e-Najara": "قلعه نجاره",
  "Qala-e-Naw": "قلعه نو",
  "Qala-e-Qazi": "قلعه قاضی",
  "Qala-e-Wahid": "قلعه وحید",
  "Qalai Fatullah": "قلعه فتح الله",
  "Qalai Mohammadi": "قلعه محمدی",
  "Qalai Naeem": "قلعه نعیم",
  "Qalai Shada": "قلعه شادا",
  "Qalai Wazir": "قلعه وزیر",
  "Qalai Zaman Khan": "قلعه زمان خان",
  "Qalai Zaman Khan-e-Hairatan": "قلعه زمان خان حیرتان",
  Qargha: "قرغه",
  Qasaba: "قصبه",
  "Sarai Shamali": "سرای شمالی",
  Sarobi: "سروبی",
  "Shakar Dara": "شکردره",
  "Shah Shaheed": "شاه شهید",
  "Shar-e-Naw": "شار نو",
  "Shash Darak": "شش درک",
  Taimani: "تیمانی",
  "Taimani Square": "میدان تیمانی",
  "Taimani-Karte-Parwan": "تیمانی - کارت پروان",
  Taimoori: "تیموری",
  "Taimoori Watt": "وطی تیموری",
  "Tapa-e-Nader Khan": "تپه نادر خان",
  "Teppe Maranjan": "تپه مرنجان",
  Wazirabad: "وزیرآباد",
  "Zarnegar Park": "پارک زرنگار",
};
